// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

When newly vended AWS Control Tower managed account is enrolled, the solution will automatically setup the IAM role for New Relic Integration. If you include existing AWS accounts in the deployment, you can immediately test and verify the deployment. Verify the deployment result from New Relic console.

* https://one.newrelic.com[Login] to New Relic using your credential.
* Follow instruction to view your AWS https://docs.newrelic.com/docs/integrations/amazon-integrations/get-started/introduction-aws-integrations/#insights[integration]

== Cleaning Up
=== Clean up the Quick Start
If the Quick Start is no longer needed, follow these steps to clean up the Quick Start AWS CloudFormation stack and stackset deployment.

WARNING: Deleting {partner-product-short-name} Quick Start template will also deletes New Relic IAM roles deployed on all AWS accounts. This Quick Start doesn't support deletion of AWS Integration on New Relic console. Ensure that you also complete the deletion of AWS Integration from New Relic console.

=== Clean up AWS CloudFormation

Time to complete clean up will vary based on how many AWS accounts is included in your {partner-product-name} deployment. CloudFormation stack deletion may timeout and it's safe to retry it.

. Open the AWS CloudFormation console, and delete the {partner-product-name} base stack to clean up all AWS resources deployed by the Stack and StackSet. This action will also delete all StackSet instances, which include IAM role deployed on each linked AWS account. 
. After base stack is deleted, navigate to AWS CloudFormation https://console.aws.amazon.com/cloudformation/home#/stacksets[StackSet]. Search for New Relic stackset and confirm the StackSet has been deleted.

=== Uninstall New Relic AWS Integration

Ensure that AWS CloudFormation clean up has been completed before you proceed. New Relic IAM roles will be removed by now and you are not required to login to each AWS account to delete it.

* https://one.newrelic.com[Login] to New Relic using your credential.
* Follow instruction here to https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-integrations/#uninstall-aws[uninstall AWS integrations]

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

For complete list of best practices for {partner-product-short-name}, please check https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/infrastructure-monitoring-best-practices-guide/[Infrastructure monitoring best practices guide]

Please refer to https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/[New Relic best practices guides] for complete list of all other best practices guides.

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

To enhance your own security measures, you can use New Relic https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/[SAML single sign-on (SSO) providers], adjust https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode/[high security mode] settings, and review https://docs.newrelic.com/docs/insights/event-data-sources/default-events/query-account-audit-logs-nrauditevent/[audit logs]. 

Visit https://docs.newrelic.com/docs/security/[New Relic security] for complete detail of New Relic security and privacy.
