// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

When you enroll a new AWS Control Tower–managed account, the deployment sets up the IAM role for {partner-product-short-name}. If you have existing AWS accounts, you can immediately test and verify the deployment's results from the New Relic console.

. https://one.newrelic.com[Log in^] to New Relic.
. To view your AWS data, see https://docs.newrelic.com/docs/integrations/amazon-integrations/get-started/introduction-aws-integrations/#insights[Introduction to AWS integrations^].

== Cleanup
If the deployment is no longer needed, follow these steps to remove the AWS CloudFormation stack and StackSet.

WARNING: Deleting the {partner-product-short-name} Quick Start template also deletes the New Relic IAM roles deployed in your AWS accounts. This Quick Start cannot, however, remove the New Relic integration, so ensure that you also delete the integration from the New Relic console.

=== Remove the AWS CloudFormation stack

The time to complete this step depends on how many AWS accounts are included in your {partner-product-name} deployment. If deleting the AWS CloudFormation stack times out, it's safe to retry this step.

. Sign in to the https://console.aws.amazon.com/console/home[AWS CloudFormation console^].
. Delete the {partner-product-name} stack to remove all AWS resources deployed by the stack. This also deletes all StackSet instances, which include any IAM roles deployed through linked AWS accounts. 
. When the stack is deleted, navigate to AWS CloudFormation https://console.aws.amazon.com/cloudformation/home#/stacksets[StackSet^], and search for the New Relic StackSet to confirm it was removed.

=== Uninstall the New Relic integration

After you confirm that the AWS CloudFormation stack was removed, remove the New Relic IAM roles. You are not required to log in to each AWS account to complete this step.

* https://one.newrelic.com[Log in^] to New Relic.
* To uninstall the AWS integration from New Relic, see https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-integrations/#uninstall-cloud[Uninstall infrastructure integrations^].

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

For a list of best practices for {partner-product-short-name}, see the https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/infrastructure-monitoring-best-practices-guide/[Infrastructure monitoring best practices guide^].

For further guidance, see https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/[Best practices guides^].

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

To enhance your security, see New Relic's https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/saml-service-providers/[Intro to authentication (SAML SSO) for users on original user model^]. Modify the https://docs.newrelic.com/docs/agents/manage-apm-agents/configuration/high-security-mode/[high-security mode^] settings, and review the https://docs.newrelic.com/docs/insights/event-data-sources/default-events/query-account-audit-logs-nrauditevent/[audit logs]. For more information about New Relic security measures, see https://docs.newrelic.com/docs/security/[Security and privacy^]. 
