=== Confirm your AWS account configuration

. Sign in to your AWS Control Tower management account with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. Open the page for the {marketplace_listing_url}[{partner-product-short-name} AMI in AWS Marketplace^], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start
// Adapt the following warning to your Quick Start.
WARNING: If you intend to enroll existing AWS accounts into {partner-product-short-name}, make sure that your AWS accounts have been enrolled into AWS Control Tower. This Quick Start doesn't support enrolling AWS accounts from AWS organization outside of your existing AWS Control Tower organization. Ensure that list of existing AWS accounts are formatted as comma-delimited string, i.e.: `account_id1,account_id2,account_id3`. 

Each deployment takes about {deployment_time} to complete. If you include existing AWS accounts in the deployment, budget for additional time to complete the deployment.

. Sign in to your AWS Control Tower management account, and choose the link below to launch the AWS CloudFormation template as a Stack. For help with choosing an option, see link:#_deployment_options[Deployment options] earlier in this guide.

** https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=NewRelic-AWS-ControlTower-Integration&templateURL=https://wellsiau-quickstart.s3.amazonaws.com/newrelic/templates/control-tower-customization.yml[CloudFormation Create Stack Link]

. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where AWS Control Tower is deployed. For other choices, see link:#_supported_regions[Supported Regions] earlier in this guide. Choose *Next* to continue.

. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide. When you finish reviewing and customizing the parameters, choose *Next*.
