// If no preperation is required, remove all content from here

==== Prepare your AWS Control Tower account

AWS Control Tower must be deployed before launching this Quick Start. For information about setting up an AWS Control Tower landing zone, see https://docs.aws.amazon.com/controltower/latest/userguide/getting-started-with-control-tower.html[Getting Started with AWS Control Tower^]. 

==== Prepare your {partner-company-name} account

When using the https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-users/pricing-billing[New Relic One pricing plan^], you must have an active New Relic account that is subscribed to a standard or higher pricing tier. With a pay-as-you-go plan, you pay only for what you use beyond the free tier (100 GB) each month.

==== Prepare for the deployment

. {partner-company-name} account ID
+
This Quick Start integrates your landing zone with a single {partner-company-name} account. https://one.newrelic.com[Log in to your {partner-company-name} account] and find the account ID. For more information, see https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/account-id/[Account ID^].
+
. {partner-company-name} NerdGraph User key
+
For all deployment options, use a {partner-company-name} User key, and enter it as parameter in the deployment. This Quick Start uses New Relic NerdGraph API for linking your AWS accounts with {partner-company-name}. For more information, see https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/[Introduction to New Relic NerdGraph, our GraphQL API^].
+
https://one.newrelic.com[Log in to your {partner-company-name} account]. Create a User key, if you don't have one already. For more information, see https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#user-api-key[User key^].
+
. {partner-company-name} NerdGraph API endpoint
+
Determine if your {partner-company-name} account is in US or EU data center. For more information, see https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/our-eu-us-region-data-centers/[{partner-company-name} data centers]. Use the default NerdGraph endpoint unless your New Relic account uses an EU data center. For more information, see https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/#authentication[NerdGraph endpoints]
+
. (Optional) Existing AWS account ID list
+
In case you've already set up your landing zone, and want to monitor existing AWS accounts enrolled in Control Tower managed organization with {partner-company-name}, supply the list of AWS account IDs (as comma separated string).
+
* Log in to an AWS Control Tower management account.
* For a list of managed accounts, navigate to https://console.aws.amazon.com/controltower/home/accounts?[AWS Control Tower^].
* Add your AWS account IDs.
. {partner-company-name} license key
+
To export metrics to your New Relic account, you must have a license key. To generate a new key, refer to https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys [New Relic API keys^].
+