// If no preperation is required, remove all content from here

==== Prepare your AWS Control Tower account

Fully deployed AWS Control Tower is required for this solution to work. For information about setting up an AWS Control Tower landing zone, follow the instructions from https://docs.aws.amazon.com/controltower/latest/userguide/getting-started-with-control-tower.html[Getting Started with AWS Control Tower] in the AWS Control Tower User Guide. 

==== Prepare your {partner-company-name} account

An active New Relic account with Standard or higher pricing tier subscription, when using
the https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-users/pricing-billing[New Relic One pricing plan]. Don’t have an account yet? https://aws.amazon.com/marketplace/pp/B08L5FQMTG[Sign up] for a perpetually free access to New Relic, which includes 100 GB of data ingest per month, one full access user and unlimited basic users. With your New Relic One pay-as-you-go plan, you only pay for what you use beyond the free tier each month.

==== Prepare for the deployment

**1. New Relic account ID**

This Quick Start integrates your landing zone with a single **{partner-company-name}** account.
https://one.newrelic.com[Login] to your {partner-company-name} account and follow instructions to find your https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/account-id/[{partner-company-name} account ID]

**2. New Relic NerdGraph API key**

For all deployment options, you need to generate {partner-company-name} User API key and enter it as parameter in the Quick Start deployment. This Quick Start uses **{partner-company-name} NerdGraph** for integration between AWS Control Tower and {partner-company-name}. See https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/[Introduction to New Relic NerdGraph] for more details.

https://one.newrelic.com[Login] to your New Relic account and follow instructions to https://docs.newrelic.com/docs/apis/get-started/intro-apis/new-relic-api-keys/#user-key-create[create a {partner-company-name} User API key]

**3. Optional: Launch AWS account list**

If you have existing AWS accounts managed by AWS Control Tower, you could deploy this Quick Start into these accounts by specifying comma-delimited list of AWS account id.

* Login to AWS Control Tower *management account*.
* Navigate to AWS Control Tower https://console.aws.amazon.com/controltower/home/accounts?[list of managed accounts]
* Take notes of AWS Account IDs that you want to be included.
