// If no preperation is required, remove all content from here

==== Prepare your AWS Control Tower account

Fully deployed AWS Control Tower is required as prerequisites of this solution. For information about setting up an AWS Control Tower landing zone, follow instruction from https://docs.aws.amazon.com/controltower/latest/userguide/getting-started-with-control-tower.html[Getting Started with AWS Control Tower] in the AWS Control Tower User Guide. 

==== Prepare your {partner-company-name} account

Active {partner-company-name} account is required with **Infrastructure Pro** enabled. Please refer to options below to get your license.

* Subscribe New Relic from https://aws.amazon.com/marketplace/seller-profile?id=cea9ae0f-34a2-4b53-aabf-5cf5c2c67938[AWS Marketplace]
* Register for New Relic https://newrelic.com/signup[free tier access] to get started. 

Once you subscribed to the solution, follow the email instruction for validation and further instruction to activate your account.

==== Prepare for the deployment

**1. New Relic Account Id**

This Quick Start integrates with single **{partner-company-name} Account Id**. Follow instruction below to collect your account id.

* https://one.newrelic.com[Login] to New Relic using your credential.
* Follow instruction on the link to find your https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/account-id/[{partner-company-name} Account ID]

**2. New Relic NerdGraph setup**

For all deployment options, you need to generate {partner-company-name} User API key and enter it as parameter in the Quick Start deployment. This Quick Start uses **{partner-company-name} NerdGraph** for integration between AWS Control Tower and {partner-company-name}. See https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/[Introduction to New Relic NerdGraph] for more detail.

* https://one.newrelic.com[Login] to New Relic using your credential.
* Follow instruction on the link to https://docs.newrelic.com/docs/apis/get-started/intro-apis/new-relic-api-keys/#user-key-create[create a {partner-company-name} User API key]

**3. Optional: Launch AWS account list**

If you have existing AWS accounts managed by AWS Control Tower, you could deploy this Quick Start into these accounts by specifying comma-delimited list of AWS account id.

* Login to AWS Control Tower *management account*.
* Navigate to AWS Control Tower https://console.aws.amazon.com/controltower/home/accounts?[list of managed accounts]
* Take notes of AWS Account IDs that you want to be included.
